### ISSUE TITLE
`scal_kernel` missing for Linear?

### ISSUE THREAD

**Issue by darkmatter08** [adityaiitb/pyprof2#4]
Hi Aditya --

I recently tried to profile a simple network like this:
```
==============================
model:
NetLayer(
  (model): Sequential(
    (linear_pyTorch0): Linear(in_features=784, out_features=8192, bias=True)
    (relu0): ReLU()
    (linear_pyTorch1): Linear(in_features=8192, out_features=8192, bias=True)
    (relu1): ReLU()
    (linear_pyTorch2): Linear(in_features=8192, out_features=10, bias=True)
  )
)
==============================
```

It's composed of pyTorch Linear layers -- `torch.nn.Linear()`. The code ran successfully, but when generating the csv, the program crashed (log below). It appears `scal_kernel` is missing from the bias kernels in the Linear layer. I didn't investigate much into how to fix this -- it seems similar to the last bug in #3. I've attached the full net.dict file to reproduce (please unzip).

Would it be possible for you to look into fixing this? Again, this tool is great! Thanks very much!

```
root@b8c74d737c70:~/code/pyprof2# python -m pdb pyprof2/prof/prof.py --csv net.dict
> /root/code/pyprof2/pyprof2/prof/prof.py(14)<module>()
-> """
(Pdb) c
"Idx","Direction","Sub","Module","Op","Kernel","Params","Sil(ns)"
"1","fprop","0","torch.nn.functional","bias","elementwise_kernel","M=8192,N=256,fp32,","32287"
"2","fprop","1","torch.nn.functional","linear","maxwell_sgemm_128x128_tn","M=8192,N=256,K=784,fp32,","552122"
"3","fprop","0","torch.nn.functional","relu","elementwise_kernel","T=(256,8192),fp32,","40512"
"4","fprop","0","torch.nn.functional","bias","elementwise_kernel","M=8192,N=256,fp32,","30496"
"5","fprop","1","torch.nn.functional","linear","maxwell_sgemm_128x128_tn","M=8192,N=256,K=8192,fp32,","4816812"
"6","fprop","0","torch.nn.functional","relu","elementwise_kernel","T=(256,8192),fp32,","40415"
"7","fprop","0","torch.nn.functional","bias","elementwise_kernel","M=10,N=256,fp32,","3648"
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/pdb.py", line 1701, in main
    pdb._runscript(mainpyfile)
  File "/opt/conda/lib/python3.7/pdb.py", line 1570, in _runscript
    self.run(statement)
  File "/opt/conda/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/root/code/pyprof2/pyprof2/prof/prof.py", line 14, in <module>
    """
  File "/root/code/pyprof2/pyprof2/prof/prof.py", line 222, in main
    xx = foo(mod, op, d)
  File "/root/code/pyprof2/pyprof2/prof/prof.py", line 58, in foo
    xx = Linear(d)
  File "pyprof2/prof/linear.py", line 87, in __init__
    assert (d.name in Linear.biasKernels)
AssertionError
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /root/code/pyprof2/pyprof2/prof/linear.py(87)__init__()
-> assert (d.name in Linear.biasKernels)
(Pdb) !d.name
'scal_kernel'
(Pdb) !d
<data.Data object at 0x7f8ce49429d0>
(Pdb) !vars(d)
{'tid': 2826868544, 'device': 0, 'stream': 7, 'grid': '1,8,1', 'block': '256,1,1', 'name': 'scal_kernel', 'lName': 'void scal_kernel<float, float, 1, false, 6, 5, 5, 3>(cublasTransposeParams<float>, float const*, float*, float const*)', 'sil': 6528, 'index': None, 'argMarker': ["{'mod': 'torch.nn.functional', 'op': 'linear', 'args': [{'name': '', 'type': 'tensor', 'shape': (256, 8192), 'dtype': 'float32'}, {'name': '', 'type': 'tensor', 'shape': (10, 8192), 'dtype': 'float32'}, {'name': '', 'type': 'tensor', 'shape': (10,), 'dtype': 'float32'}]}", "{'mod': 'torch', 'op': 'addmm', 'args': [{'name': '', 'type': 'tensor', 'shape': (10,), 'dtype': 'float32'}, {'name': '', 'type': 'tensor', 'shape': (256, 8192), 'dtype': 'float32'}, {'name': '', 'type': 'tensor', 'shape': (8192, 10), 'dtype': 'float32'}]}"], 'modMarker': [], 'seqMarker': ['addmm, seq = 557'], 'layer': [], 'trace': ['main_joint.py:113', 'main_joint.py:90', '/root/code/util.py:233', '/root/code/util.py:137', '/root/code/model.py:92', '/root/.local/lib/python3.7/site-packages/pyprof2/nvtx/nvmarker.py:95'], 'seqId': [557], 'altSeqId': [], 'dir': 'fprop', 'sub': 1, 'mod': 'na', 'op': 'na', 'params': {'na': 'na'}, 'tc': 'na', 'flops': 0, 'bytes': 0}
(Pdb)
```

[net_pyTorch_linear.zip](https://github.com/adityaiitb/pyprof2/files/4738898/net_pyTorch_linear.zip)

**Comment by adityaiitb** [comment]
Absolutely, I will take a look. Thanks for using the tool and reporting bugs. Typically you don't have to use `pdb`. The tool has a lot of assertions, which is generally good enough for me.

**Comment by adityaiitb** [comment]
Fixed and pushed. I just had to add the kernel to the list of bias kernels. I can now run the dictionary successfully. Please confirm and then I will close the bug.

**Comment by darkmatter08** [comment]
Sorry for the delay -- it works. Thanks very much!

I have a few more questions (I can break it out into a separate issue if that's better).
~~1. Why is torch.randperm() not profiled? It is [implemented in CUDA](https://github.com/pytorch/pytorch/pull/7606).~~ Edit: just realized I needed to write `torch.randperm(80, device='cuda')` for this to actually run on GPU. However, after this change, there's a profiling issue with pyprof. I will create another issue for this. (Didn't realize this was required as similar ops like `torch.multinomial()` dont require specifying device.)
2. Allocations don't seem to be profiled. Why is this the case? How can I figure out the runtime costs of allocing tensors?
3. If I use pyTorch's TorchScript / JIT tool -- how will this tool behave? Will it still generate profiling results that are meaningful and interpretable? 
4. If I use the tool without `with torch.autograd.profiler.emit_nvtx():` wrapping the block of interest, but still use `profiler.start()`, `profiler.stop()` to wrap the block of interest, will I simply lose the backward pass profiling while still getting accurate forward pass profiling?
5. Lastly, how is this tool different than nvidia's pyprof tool? I haven't used that tool. Will this tool become an official tool as well?

Again, thanks for developing and sharing this tool!

**Comment by darkmatter08** [comment]
Hi Aditya -- A few more follow up questions.

- How representative profiling runtime results vs normal runtime results? I understand the profiler introduces overhead, and therefore should not be used when benchmarking the best overall runtime, for example. However, is the overhead fixed per operation, or not? In other words, if I have operations A, B, C, which have runtime tA, tB, and tC, respectively, and pyprof2 reports runtimes of tA', tB', tC', respectively, can I safely assume the ratios tA'/tB' and tA/tC match their un-profiled runtimes tA/tB and tA/tC as well?
For context, what I'm trying to do is replace a single expensive op/kernel in my network with multiple smaller cheap operations. I'm interested in seeing how much runtime each of the cheap ops takes as compared to the expensive op. I'm trying to figure out if these ratios are a valid way to compare. 
- Is there a way to automatically match profiling results to the pytorch code? 
It's easy to match up profiling results the code when you profile a small example with minimal LOC. (I use the provided fields "Idx, Direction, Sub, Module, Op, Kernel, Params" to help match). However, if I profile a complex piece of code like a TransformerEncoderLayer from Fairseq, even for 1 iter, I get so many kernels that it becomes difficult to match kernels to pytorch calls. So, is there a better way to match kernels to code? Or is the recommended way to use a profiler to create small examples with minimal LOCs?
Edit: Ah, I just discovered the "-c trace" option, which seems to hit this on the head.

Thanks again for taking the time to answer all of these questions. This tool is very promising, and I hope more people will learn about it!

**Comment by adityaiitb** [comment]
> 1. Why is torch.randperm() not profiled? It is [implemented in CUDA](https://github.com/pytorch/pytorch/pull/7606).~ Edit: just realized I needed to write `torch.randperm(80, device='cuda')` for this to actually run on GPU. However, after this change, there's a profiling issue with pyprof. I will create another issue for this. (Didn't realize this was required as similar ops like `torch.multinomial()` dont require specifying device.)

Thanks for the fix.

> 2. Allocations don't seem to be profiled. Why is this the case? How can I figure out the runtime costs of allocing tensors?

This is what I understand. PyTorch uses a caching allocator. It reserves a huge chunk of GPU memory upfront and then manages that memory pool itself instead of using cuda malloc / free every time a tensor is created / destroyed. The cost of this memory management is typically small (a few us I have heard), is incurred on the CPU and you will not see any CUDA API calls if you were expecting one. I don't have pointers on where is the code which does this. Once you know the function, estimating the cost should be easy.

> 3. If I use pyTorch's TorchScript / JIT tool -- how will this tool behave? Will it still generate profiling results that are meaningful and interpretable?

The tool will behave as before. However, you have to follow the correct initialization sequence. You should not initialize pyprof before any JIT has finished, otherwise the JIT will fail. See the second question here https://github.com/adityaiitb/pyprof2/blob/master/pyprof2/FAQs.md. I have a solution in the works which will allow profiling a JITted function as well. Note that for JITted functions, the tool can (in the future) capture the input arguments but cannot calculate the bytes and flops because it cannot know what is inside the black box (the JITted function).

> 4. If I use the tool without `with torch.autograd.profiler.emit_nvtx():` wrapping the block of interest, but still use `profiler.start()`, `profiler.stop()` to wrap the block of interest, will I simply lose the backward pass profiling while still getting accurate forward pass profiling?

Everything will still be profiled (fprop and bprop). Pyprof will also work seamlessly and you will still get all the vanilla NVprof information e.g. kernel name, duration, grid and block dimensions etc. What you lose is the ability to correlate the bprop call to the corresponding fprop call i.e. the tool will no longer be able to say "this convolution in bprop is related to this convolution in fprop". Very short answer: Essentially what `emit_nvtx` does is that it records the `sequence id` for all fprop and bprop calls. The tool uses these ids to do the linking. Very nicely documented here: https://pytorch.org/docs/stable/autograd.html#torch.autograd.profiler.emit_nvtx

> 5. Lastly, how is this tool different than nvidia's pyprof tool? I haven't used that tool. Will this tool become an official tool as well?

Its exactly the same tool, same authors. Very minute difference in usage. Earlier it was part of Nvidia APEX, but now its in a repository of its own which makes development and contributions easier. Short answer: I would recommend using that tool moving ahead. I didn't mention it earlier so as to not confuse you. You might hit the same bugs. I am working on pushing the changes to that repo to achieve parity.

**Comment by adityaiitb** [comment]
> How representative profiling runtime results vs normal runtime results? I understand the profiler introduces overhead, and therefore should not be used when benchmarking the best overall runtime, for example. However, is the overhead fixed per operation, or not? In other words, if I have operations A, B, C, which have runtime tA, tB, and tC, respectively, and pyprof2 reports runtimes of tA', tB', tC', respectively, can I safely assume the ratios tA'/tB' and tA/tC match their un-profiled runtimes tA/tB and tA/tC as well?

There are two times
- Kernel execution time on the GPU (NVprof and pyprof report this time).
- The wall clock time.

The GPU profiler (NVprof / Nsight) and tools built on top e.g. pyprof do not impact the GPU kernel execution time. The wall clock time is impacted because e.g. pyprof is intercepting code, parsing input arguments, creating (potentially big) NVTX markers and inserting them into a database. The amount of work is variable e.g. a concat operation can have two tensors or 20 tensors.

From what you described, tA almost= tA' and so on (after some warm up iterations). Also if the GPU kernels are big (about 100 us) the CPU cost gets hidden and wall clock time ~= sum of GPU kernel time.

>   For context, what I'm trying to do is replace a single expensive op/kernel in my network with multiple smaller cheap operations. I'm interested in seeing how much runtime each of the cheap ops takes as compared to the expensive op. I'm trying to figure out if these ratios are a valid way to compare.

You should be able to sum up the GPU kernel times in both cases and compare. However, if you break the op into multiple small ops (about 20 us), then you might see a slowdown because of the CPU getting in the critical path (irrespective of the profiler being on or off). Profiling on in such a situation will make the CPU look even worse.

> * Is there a way to automatically match profiling results to the pytorch code?
>   It's easy to match up profiling results the code when you profile a small example with minimal LOC. (I use the provided fields "Idx, Direction, Sub, Module, Op, Kernel, Params" to help match). However, if I profile a complex piece of code like a TransformerEncoderLayer from Fairseq, even for 1 iter, I get so many kernels that it becomes difficult to match kernels to pytorch calls. So, is there a better way to match kernels to code? Or is the recommended way to use a profiler to create small examples with minimal LOCs?
>   Edit: Ah, I just discovered the "-c trace" option, which seems to hit this on the head.

:) Yes, we realized early on that stack trace was absolutely vital to navigate complex code.
 
> Thanks again for taking the time to answer all of these questions. This tool is very promising, and I hope more people will learn about it!

:) I am glad you find it useful. Please spread the word.

**Comment by darkmatter08** [comment]
> Also if the GPU kernels are big (about 100 us) the CPU cost gets hidden and wall clock time ~= sum of GPU kernel time.
> You should be able to sum up the GPU kernel times in both cases and compare. However, if you break the op into multiple small ops (about 20 us), then you might see a slowdown because of the CPU getting in the critical path (irrespective of the profiler being on or off). Profiling on in such a situation will make the CPU look even worse.

So my understanding is the profiler doesn't capture CPU time. CPU time will likely increase if I break a single big kernel into multiple smaller kernels, because each kernel needs to be launched by the CPU. And the CPU overhead per kernel is roughly the same, assuming all tensors are already on GPU (as to avoid memory copying RAM <> VRAM). 
I'd like to get a ballpark idea of this CPU overhead. Is there a 'rule of thumb' number I can use? I've noticed discrepancies in the runtime reported by pyprof2 and simple pytorch CUDA event timers (snippet below). Am I correct in saying all of this discrepancy is a result of the CPU overhead?
```
    start = torch.cuda.Event(True)
    end = torch.cuda.Event(True)
    start.record()
    # do some compute.
    end.record()
    end.synchronize()
    print(start.elapsed_time(end)) # reported in miliseconds (ms).
```
